Repository dwyl/mvp, pull requests merged in 2019-11, with the labels that each got.

#17 add .travis.yml configuration file
  .gitignore
  .travis.yml
  assets/package-lock.json
  mix.exs
Labels: in-progress

#18 PR: Rename Kinds to Tags for Simplicity
  README.md
  assets/package-lock.json
  config/config.exs
  lib/app/ctx.ex
  lib/app/ctx/item.ex
  lib/app/ctx/list.ex
  lib/app/ctx/person.ex
  lib/app/ctx/status.ex
  lib/app/ctx/tag.ex
  lib/app_web/controllers/kind_controller.ex
  lib/app_web/controllers/tag_controller.ex
  lib/app_web/endpoint.ex
  lib/app_web/router.ex
  lib/app_web/templates/kind/edit.html.eex
  lib/app_web/templates/kind/index.html.eex
  lib/app_web/templates/kind/new.html.eex
  lib/app_web/templates/kind/show.html.eex
  lib/app_web/templates/tag/edit.html.eex
  lib/app_web/templates/tag/form.html.eex
  lib/app_web/templates/tag/index.html.eex
  lib/app_web/templates/tag/new.html.eex
  lib/app_web/templates/tag/show.html.eex
  lib/app_web/views/kind_view.ex
  lib/app_web/views/tag_view.ex
  priv/repo/migrations/20191113100513_create_tags.exs
  priv/repo/migrations/20191113100912_create_status.exs
  priv/repo/migrations/20191113100920_create_people.exs
  priv/repo/migrations/20191113100927_create_items.exs
  priv/repo/migrations/20191113100933_create_lists.exs
  priv/repo/migrations/20191113100938_create_timers.exs
  priv/repo/migrations/20191113114340_add_person_id_to_tag.exs
  priv/repo/migrations/20191113141229_add_person_id_to_status.exs
  priv/repo/migrations/20191113144142_create_list_items_association.exs
  priv/repo/migrations/20191113195733_create_item_tags_association.exs
  test/app/ctx_test.exs
  test/app_web/controllers/kind_controller_test.exs
  test/app_web/controllers/tag_controller_test.exs
Labels: in-review

#19 configure application for heroku
  .gitignore
  Procfile
  README.md
  app.json
  config/config.exs
  config/prod.exs
  elixir_buildpack.config
  lib/app_web/endpoint.ex
Labels: awaiting-review

#22 add capture endpoint
  assets/css/app.css
  assets/css/tachyons.css
  assets/static/images/submit.png
  lib/app_web/controllers/captures_controller.ex
  lib/app_web/controllers/categorise_controller.ex
  lib/app_web/router.ex
  lib/app_web/templates/capture/new.html.eex
  lib/app_web/templates/categorise/_capture.html.eex
  lib/app_web/templates/categorise/index.html.eex
  lib/app_web/templates/item/index.html.eex
  lib/app_web/templates/layout/app.html.eex
  lib/app_web/templates/page/index.html.eex
  lib/app_web/views/capture_view.ex
  lib/app_web/views/categorise_view.ex
  priv/repo/migrations/20191115144039_update_item_text_type.exs
  test/app_web/controllers/capture_controller_test.exs
  test/app_web/controllers/categorise_controller_test.exs
  test/app_web/controllers/page_controller_test.exs
Labels: in-review
