Repository dwyl/mvp, pull requests merged in 2022-12, with the labels that each got.

#223 Style links as buttons for login logout
  lib/app_web/templates/layout/root.html.heex
Labels: T25m, awaiting-review, tech-debt

#225 PR: DRY Assign JWT to Socket Code issue #215
  BUILDIT.md
  lib/app_web/controllers/auth_controller.ex
Labels: enhancement, in-progress, technical, priority-2, chore, T5m, tech-debt

#227 PR: Update `deps`
  mix.exs
  mix.lock
Labels: T25m, awaiting-review, technical, chore, tech-debt

#230 PR: Create Review Apps
  .github/scripts/review-apps.sh
  .github/workflows/review-apps.yml
  build-review-apps.md
  lib/app_web/live/app_live.html.heex
Labels: awaiting-review
