Repository dwyl/mvp, pull requests merged in 2022-10, with the labels that each got.

#159 Edit item's tags
  assets/css/app.css
  assets/tailwind.config.js
  config/config.exs
  lib/app/color.ex
  lib/app/item.ex
  lib/app/tag.ex
  lib/app_web.ex
  lib/app_web/controllers/tag_controller.ex
  lib/app_web/live/app_live.ex
  lib/app_web/live/app_live.html.heex
  lib/app_web/router.ex
  lib/app_web/templates/layout/app.html.heex
  lib/app_web/templates/layout/nav.html.heex
  lib/app_web/templates/layout/root.html.heex
  lib/app_web/templates/tag/edit.html.heex
  lib/app_web/templates/tag/form.html.heex
  lib/app_web/templates/tag/index.html.heex
  lib/app_web/views/tag_view.ex
  mix.exs
  mix.lock
  priv/repo/migrations/20220930212128_add_color_to_tag.exs
  test/app/tag_test.exs
  test/app_web/controllers/tag_controller_test.exs
  test/app_web/live/app_live_test.exs
Labels: in-review

#164 Update dependencies
  mix.lock
Labels: awaiting-review

#162 Create people migration
  .iex.exs
  lib/app/item.ex
  lib/app/person.ex
  lib/app/tag.ex
  lib/app_web/controllers/init_controller.ex
  lib/app_web/controllers/profile_controller.ex
  lib/app_web/controllers/tag_controller.ex
  lib/app_web/router.ex
  lib/app_web/templates/layout/root.html.heex
  lib/app_web/templates/profile/edit.html.heex
  lib/app_web/views/profile_view.ex
  priv/repo/migrations/20221004195054_add_person.exs
  test/app/item_test.exs
  test/app/person_test.exs
  test/app/tag_test.exs
  test/app/timer_test.exs
  test/app_web/controllers/profile_controller_test.exs
  test/app_web/controllers/tag_controller_test.exs
  test/app_web/live/app_live_test.exs
Labels: in-review

#171 Update dependencies
  mix.exs
  mix.lock
Labels: awaiting-review

#182 Remove check on person name
  lib/app/person.ex
  lib/app_web/router.ex
  mix.lock
  test/app/person_test.exs
  test/app_web/controllers/profile_controller_test.exs
Labels: awaiting-review

#184 Add LiveView formatter
  .formatter.exs
  .github/workflows/ci.yml
  lib/app_web/live/app_live.html.heex
  lib/app_web/templates/layout/icons.html.heex
  lib/app_web/templates/layout/nav.html.heex
  lib/app_web/templates/layout/root.html.heex
  lib/app_web/templates/profile/edit.html.heex
  lib/app_web/templates/tag/edit.html.heex
  lib/app_web/templates/tag/form.html.heex
  lib/app_web/templates/tag/index.html.heex
  mix.exs
  mix.lock
Labels: in-review

#186 Run mix format
  lib/app_web/router.ex
Labels: awaiting-review

#187 Update Elixir to 1.14
  .github/workflows/ci.yml
  Dockerfile
  mix.exs
  mix.lock
Labels: awaiting-review

#189 Update Tailwind to use v3.2
  config/config.exs
Labels: awaiting-review

#192 [PR] Updating README and BUILD.
  BUILDIT.md
  README.md
Labels: in-review, chore
