Repository dwyl/mvp, pull requests merged in 2022-08, with the labels that each got.

#117 Use Alpine.js and Tailwind for Textarea size
  lib/app_web/live/app_live.html.heex
Labels: awaiting-review

#124 Update dependencies
  .env_sample
  mix.exs
  mix.lock
Labels: awaiting-review

#125 Filter items by status
  BUILDIT.md
  lib/app/item.ex
  lib/app_web/live/app_live.ex
  lib/app_web/live/app_live.html.heex
  test/app_web/live/app_live_test.exs
Labels: awaiting-review

#127 Define filter status
  BUILDIT.md
  lib/app/item.ex
  lib/app_web/live/app_live.ex
  lib/app_web/live/app_live.html.heex
  test/app_web/live/app_live_test.exs
Labels: awaiting-review

#130 PR: Improve Accessibility #129
  lib/app_web/live/app_live.ex
  lib/app_web/live/app_live.html.heex
  lib/app_web/templates/layout/icons.html.heex
  lib/app_web/templates/layout/live.html.heex
  lib/app_web/templates/layout/root.html.heex
Labels: awaiting-review, T5m

#132 Remove Items query on filter
  BUILDIT.md
  lib/app_web/live/app_live.ex
  test/app_web/live/app_live_test.exs
Labels: awaiting-review

#135 Update syntax for get_person_id function
  lib/app_web/live/app_live.ex
Labels: awaiting-review

#138 PR: Remove Unused Environment Variables from `ci.yml` #133
  .github/workflows/ci.yml
Labels: awaiting-review, T5m, tech-debt
