Repository dwyl/mvp, pull requests merged in 2023-02, with the labels that each got.

#288 PR: Add plausible analytics issue #287
  lib/app_web/templates/layout/root.html.heex
Labels: enhancement, help wanted, awaiting-review, technical, priority-1, chore, T5m

#289 PR: add Content-Security-Policy to root.html
  lib/app_web/templates/layout/root.html.heex
Labels: help wanted, awaiting-review, technical, priority-1, T5m

#290 Update csp
  lib/app_web/templates/layout/root.html.heex
Labels: awaiting-review

#291 PR: inline both plausible and cloudflare in CSP #287
  lib/app_web/templates/layout/root.html.heex
Labels: awaiting-review, technical, T5m

#292 PR: Simplify Content-Security-Policy #287
  lib/app_web/templates/layout/root.html.heex
Labels: awaiting-review, technical, T5m

#293 Update content-policy
  lib/app_web/templates/layout/icons.html.heex
  lib/app_web/templates/layout/root.html.heex
Labels: awaiting-review

#294 Place CSP in root.html
  BUILDIT.md
  lib/app_web/templates/layout/icons.html.heex
  lib/app_web/templates/layout/root.html.heex
Labels: awaiting-review

#299 [PR] Fix failing API tests.
  lib/api/localhost.json
Labels: awaiting-review, chore, BLOCKED

#298 PR: move selected `tags` above `tags` selector #296
  lib/app_web/live/app_live.html.heex
Labels: awaiting-review, T5m

#306 Call resize() on x:init
  lib/app_web/live/app_live.html.heex
Labels: awaiting-review

#323 [PR] Upgrading to Phoenix 1.7
  .formatter.exs
  BUILDIT.md
  lib/api/MVP.json
  lib/app_web.ex
  lib/app_web/endpoint.ex
  lib/app_web/live/app_live.html.heex
  mix.exs
  mix.lock
  test/support/conn_case.ex
Labels: in-review, chore, elixir
