Repository dwyl/mvp, pull requests merged in 2023-01, with the labels that each got.

#250 [PR] Adding basic table and metrics page
  BUILDIT.md
  README.md
  lib/app/item.ex
  lib/app/person.ex
  lib/app/tag.ex
  lib/app/timer.ex
  lib/app_web/controllers/profile_controller.ex
  lib/app_web/live/app_live.ex
  lib/app_web/live/stats_live.ex
  lib/app_web/live/stats_live.html.heex
  lib/app_web/router.ex
  lib/app_web/templates/layout/root.html.heex
  lib/app_web/templates/profile/edit.html.heex
  priv/repo/migrations/20221004195054_add_person.exs
  test/app/item_tag_test.exs
  test/app/item_test.exs
  test/app/person_test.exs
  test/app/tag_test.exs
  test/app/timer_test.exs
  test/app_web/controllers/profile_controller_test.exs
  test/app_web/controllers/tag_controller_test.exs
  test/app_web/live/app_live_test.exs
  test/app_web/live/stats_live_test.exs
Labels: enhancement, in-review

#260 Do not create review app for dependabot PRs
  .github/workflows/review-apps.yml
Labels: awaiting-review

#255 [PR] Adding Papertrail and recording changes
  BUILDIT.md
  config/config.exs
  lib/app/item.ex
  lib/app_web/live/app_live.ex
  mix.exs
  mix.lock
  priv/repo/migrations/20230110115305_add_versions.exs
  test/app/item_test.exs
  test/app/timer_test.exs
  test/app_web/live/app_live_test.exs
  test/app_web/live/stats_live_test.exs
Labels: enhancement, in-review, elixir

#262 [PR] Fixes stats page not loading and erronous incrementing
  BUILDIT.md
  lib/app/item.ex
  lib/app_web/live/stats_live.ex
  test/app_web/live/stats_live_test.exs
Labels: bug, awaiting-review

#263 [PR] Stage 1 - No `auth`, anonymous API for `Timers` and `Items`
  API.md
  BUILDIT.md
  lib/api/item.ex
  lib/api/timer.ex
  lib/app/datetime_parser.ex
  lib/app/item.ex
  lib/app/timer.ex
  lib/app_web/router.ex
  mix.exs
  test/api/item_test.exs
  test/api/timer_test.exs
  test/app/timer_test.exs
  test/app_web/live/app_live_test.exs
Labels: bug, enhancement, awaiting-review, technical

#254 Create draft item
  lib/app/item.ex
  lib/app_web/live/app_live.ex
  lib/app_web/live/app_live.html.heex
Labels: awaiting-review

#276 [PR] Adding Hoppscotch CLI testing
  .github/workflows/ci.yml
  .gitignore
  .prettierrc
  API.md
  config/test.exs
  lib/api/MVP.json
  lib/api/api_test_mock_data.sql
  lib/api/envs.json
  lib/api/localhost.json
  lib/app/timer.ex
  lib/app_web/live/app_live.html.heex
  test/api/timer_test.exs
  test/app_web/live/app_live_test.exs
  test/app_web/views/error_view_test.exs
Labels: enhancement, in-review

#279 [PR] Adding seed data for CI.
  .github/workflows/ci.yml
  API.md
  lib/api/api_test_mock_data.sql
  priv/repo/seeds.exs
Labels: awaiting-review, chore

#280 [PR] API Stage 2 - Adding tags
  API.md
  api.md
  lib/api/MVP.json
  lib/api/envs.json
  lib/api/hoppscotch.md
  lib/api/item.ex
  lib/api/localhost.json
  lib/api/tag.ex
  lib/app/item.ex
  lib/app/tag.ex
  lib/app_web/router.ex
  priv/repo/seeds.exs
  test/api/item_test.exs
  test/api/tag_test.exs
  test/api/timer_test.exs
  test/app/item_test.exs
  test/app/tag_test.exs
Labels: enhancement, in-review, elixir
